# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: "Josue Page LFM" 
masthead_title: >- 
  <i class="fas fa-microscope fa-2x" ></i> 
  <i class="fas fa-plus"></i> 
  <i class="fas fa-laptop-code fa-2x"></i> 
  <i class="fas fa-equals"></i> 
  <i class="fas fa-cube fa-2x"></i>
repository: "pvjosue/test.github.io"
email: "pv.josue@gmail.com"
description: I'm a Ph.D. candidate in the computational imaging and inverse problems group at the Technical University of Munich. 

github_username: pvjosue
minimal_mistakes_skin: mint
search: true

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
# Outputting
permalink: /:categories/:title/
config:
  paginate: nil #0 # amount of posts to show
# paginate_path: /page:num/
timezone: Europe/Berlin # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

include:
  - _pages

# Plugins (previously gems:)
plugins:
  # - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache
  - jekyll-seo-tag 
author:
  name   : "Josué Page Vizcaíno"
  avatar : "/assets/images/bio-photo.jpg"
  bio    : "PhD Student at the Technical University of Munich"
  location: "Munich, Germany"
  googlescholar: "https://scholar.google.com/citations?hl=en&user=5WfCRjQAAAAJ"
  links:
    - label: "Institutional Website"
      icon: "fas fa-fw fa-link"
      url: "https://ciip.in.tum.de/people/page.html"
    - label: "LinkedIn"
      icon: "fas fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/pvjosue"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/pvjosue/"
    - label: "Google Scholar"
      icon: "fas fa-fw fa-graduation-cap"
      url: "https://scholar.google.com/citations?hl=en&user=5WfCRjQAAAAJ"
    - label: "ORCID"
      icon: "fab fa-fw fa-orcid"
      url: "https://orcid.org/0000-0002-5848-3063"
    - label: "Open Processing"
      icon: "fab fa-product-hunt"
      url: "https://www.openprocessing.org/user/9498/"


google_site_verification: "5cB-ixj9LM-TwE__EP9Cx_5VZCxXup4zKdO3Gq4No_k"
github-cards-path: /assets/github-cards/
github-repos:
  - name: pvjosue/SLNet_XLFMNet
  - name: pvjosue/LFMNet
  - name: pvjosue/WaveBlocks
  - name: pvjosue/pytorch_convNd
  - name: pvjosue/OpenCV-Spout
  - name: pvjosue/pytorch_fftNd
  - name: pvjosue/github-cards

footer:
  links:
    - label: "Website"
      icon: "fas fa-fw fa-link"
      url: "https://"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/pvjosue/"
    - label: "Google Scholar"
      icon: "fas fa-fw fa-graduation-cap"
      url: "https://scholar.google.com/citations?hl=en&user=5WfCRjQAAAAJ"
    - label: "ORCID"
      icon: "fab fa-fw fa-orcid"
      url: "https://orcid.org/0000-0002-5848-3063"

analytics:
  provider: "google-gtag"
  google:
    tracking_id: "UA-165372182-1"
    anonymize_ip: false # default
# Collections
collections:
  ideas:
    output: true
    permalink: /:collection/:path/

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: false
      comments: true
      share: true
      related: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true
  # _ideas
  - scope:
      path: ""
      type: ideas
    values:
      layout: single
      author_profile: true
      share: true
      comments: true
  # _cv
  - scope:
      path: ""
      type: cv
    values:
      layout: single
      author_profile: true
      share: true
      comments: true

category_archive:
  type: liquid
  path: /categories/
